### ISSUE TITLE
DOMDocument::loadHTML(): Unexpected end tag : p in Entity, line: 71

### ISSUE THREAD

**Issue by Blackout8099** [SDKiller/zyx-phpmailer#12]
I have done a clean install and recieved DOMDocument::loadHTML(): Unexpected end tag : p in Entity, line: 71

any ideas??

**Comment by SDKiller** [comment]
This error is produced by [Html2Text](https://github.com/mtibben/html2text/) which is used to convert html to text (for example for message altBody).

As it relies on DOMDocument - it probably expects that html passed should be valid.

If you cannot ensure this - you may disable `Html2Text` and PHPMailer simple conversion function `html2text()` will be used https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php#L3418

To do so add to your mailer config:

```
    `html2textHandler` => false,
```

**Comment by Blackout8099** [comment]
Ahh I see now, seem so obvious now :)

I resolved all my issuses by merging both fixes from dev-master and stable. Not had an issue sinces.

**Comment by logig** [comment]
libxml_use_internal_errors(true)
