### ISSUE TITLE
PHPMailer not found

### ISSUE THREAD

**Issue by richardoctoey** [SDKiller/zyx-phpmailer#13]
hi, currently my environment is in windows. the PHPMailer version is 6.0
when `class Adapter extends \PHPMailer` it returns error, telling that PHPMailer not found.

the PHPMailer itself is already in vendor directory, and I've tried to dump-autoload.
If I add `use PHPMailer\PHPMailer\PHPMailer` and extends it, it's fine.

the getVersion is also fail in windows
`public function getVersion()
    {
        return PHPMailer::VERSION; // before return $this->Version;
    }`

if my code is correct in linux env please update, or I can commit it.

**Comment by SDKiller** [comment]
It is not currently tested with PHPMailer 6, which introduces many BC
breaks.

11 сент. 2017 г. 7:44 ПП пользователь "Richard Octovianus Oey" <
notifications@github.com> написал:
