### ISSUE TITLE
composer.json PHP mailer version

### ISSUE THREAD

**Issue by Ziggizag** [SDKiller/zyx-phpmailer#14]
SDKiller,

Please, until compatibility issue with PHP Mailer v. 6 remains unresolved, update your composer.json appropriately to prevent dependent library upgrade. It should read:

```
"require": {
        "yiisoft/yii2": "*",
        "phpmailer/phpmailer": "~5.2",   <------ HERE !!!
        "soundasleep/html2text": "*"
},
```
Best regards!

**Comment by SDKiller** [comment]
You are totally right, thank you

**Comment by Ziggizag** [comment]
@SDKiller - It's a bit nonsense:

`"phpmailer/phpmailer": "~5.2.25",`

It really should read:

either:

`"phpmailer/phpmailer": "~5.2",`

or:

`"phpmailer/phpmailer": "5.2.25",`

**Comment by Ziggizag** [comment]
IMHO:

`"phpmailer/phpmailer": "~5.2",`

is a bit more save in case they found some critical bug in this version and updated it to 5.2.26 for instance.

**Comment by SDKiller** [comment]
@Ziggizag 

According to https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

> ...while ~1.2.3 is equivalent to >=1.2.3 <1.3.0.

**Comment by Ziggizag** [comment]
Oh - I did not know!

"Keep'on learning" is always true - thank you, Serge!
