### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback, non-static method zyx\phpmailer\Mailer::processResult() should not be called statically

### ISSUE THREAD

**Issue by dryu** [SDKiller/zyx-phpmailer#2]
call_user_func_array() expects parameter 1 to be a valid callback, non-static method zyx\phpmailer\Mailer::processResult() should not be called statically

Looks like Mailer::processResult() needs to be made static.

**Comment by sergeevdan** [comment]
Thank you!
