### ISSUE TITLE
Call to undefined method zyx\phpmailer\Adapter::normalizeBreaks()

### ISSUE THREAD

**Issue by gianx89** [SDKiller/zyx-phpmailer#6]
When I send and email with this code:

```php
Yii::$app->mailer->compose()
     ->setFrom(['net@test.com' => 'My Example Site'])
     ->setTo(Yii::$app->getRequest()->getQueryParam('mailbox'))
     ->setSubject('Impostazioni mailbox')
     ->setTextBody($file)
     ->send();
```

I get this error from the debugger:

> Call to undefined method zyx\phpmailer\Adapter::normalizeBreaks()

This happens because in the **Adapter.php** file the *normalizeBreaks()* method is called:

```php
    /**
     * Sets message plain text content.
     * @param string $text message plain text conten
     * @return void
     */
    public function msgText($text)
    {
        $this->isHTML(false);
        $text = self::html2text($text, true);
        $text = self::normalizeBreaks($text);
        $this->Body = $text;
    }
```

But **not implemented**. If I comment out this call, it works like a charm. But I don't want to modify the source code downloaded via composer so, can you fix the error and make a commit?

**Comment by SDKiller** [comment]
Hi. Its strange.

`\PHPMailer::normalizeBreaks` - as `Adapter` is extended from `phpMailer` - this `phpMailer` method is called and its working for me.

Could you please try to replace `self` with `static` like this

```
$text = static::normalizeBreaks($text);
```

Check if it will work for you and let me know - I'll try to investigate the issue deeper.
